### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by 0x-Robert** [0x-Robert/online-ordering-system#1]
# API

### 피주문자

- 피주문자 회원가입
- [x] https://localhost:1323/admin/v01/register | POST | CREATE
- 피주문자 회원가입
- [x] http://localhost:8080/admin/v01/register | POST | CREATE
- 피주문자 로그인
- [x] http://localhost:8080/admin/v01/login | POST | UPDATE
- 피 주문자가 메뉴를 등록한다.
- [x] http://localhost:8080/admin/v01/menu/create | POST | CREATE
- 피 주문자가 기존 메뉴를 삭제한다.
- [x] http://localhost:8080/admin/v01/menu/delete | POST | DELETE
- 피주문자의 최신 접수내역을 확인하고 상태를 가져온다.
- [x] http://localhost:8080/admin/v01/menu/status | GET | SELECT
- 피주문자가 메뉴를 추천/비추천 할 수 있도록 업데이트 한다.
- [x] http://localhost:8080/admin/v01/menu/recom| POST | UPDATE

### 주문자

- 주문자 회원가입
- [x] http://localhost:8080/v01/register | POST | CREATE

- 주문자 로그인
- [x] http://localhost:8080/v01/login | POST | UPDATE

- 주문자 메뉴 주문
- [x] http://localhost:8080/v01/order | POST | Create
    -> 선택한 메뉴를 주문하기 (선택메뉴 정보와 주문자 정보 + 전화번호, 주소, 메뉴수량, 결제정보(현금,카드,네이버페이,카카오페이?))
    -> 대신 메뉴 추가시 상태가 배달중일 경우 실패, 신규주문으로 전환알림
    -> 메뉴 변경시 상태가 조리중, 배달중일 경우 실패알림  
    -> Order Status 보고 조건에 따라 진행

- 주문자가 특정 메뉴에 대해 리뷰를 남긴다. > 대신 상태가 배달 중 or 배달완료일때만 업데이트 가능
- [ ] http://localhost:8080/v01/menu/review | POST | UPDATE + INSTERT

### 공통
- 피 주문자,주문자가 전체 메뉴를 조회한다.
- [x] https://localhost:1323/v01/menu/all | GET | SELECT
- 피 주문자,주문자가 추천으로 필터링해서 메뉴를 조회한다.
- [ ] https://localhost:1323/v01/menu/filter/recom | GET | SELECT
- 피 주문자,주문자가 평점으로 필터링해서 메뉴를 조회한다.
 - [ ]  https://localhost:1323/v01/menu/filter/rate | GET | SELECT
- 피 주문자,주문자가 주문수로 필터링해서 메뉴를 조회한다.
- [ ]  https://localhost:1323/v01/menu/filter/count | GET | SELECT
- 피 주문자,주문자가 최신날짜기준으로 필터링해서 메뉴를 조회한다.
- [ ]  https://localhost:1323/v01/menu/filter/latest | GET | SELECT
- 피 주문자,주문자가 특정 메뉴를 조회한다.
- [x] https://localhost:1323/v01/menu/1 | GET | SELECT
- 피 주문자,주문자가 주문상태를 조회한다.
- [ ]  https://localhost:1323/v01/order/history | GET | SELECT

# Database : mini-oss

### 메뉴
  - [x] 생성
#### Collection menu

```
type Menu struct {
MenuId int `json:"menuid"`
ImageUrl string `json:"imageurl"`
Name string `json:"name"`
Quantity int `json:"quantity"`
Price int `json:"price"`
Recommendation bool `json:"recommendation"`
Admin string `json:"admin"`
Score int `json:"score"`
Review string `json:"review"`
}
```
### 주문 
  - [x] 생성
#### Collection order
```
type Order struct {
MenuName string `json:"menuname"`
Customer string `json:"customer"`
PhoneNumber string `json:"phonenumber"`
Address string `json:"address"`
Quantity int `json:"quantity"`
PaymentInformation string `json:"paymentinformation"`
Status  `json:"intake"`
}
```

#### 유저정보
  - [x] 생성
#### Collection user_account
- id / int
- user string
- password string
#### 관리자 정보
  - [x] 생성
#### Collection admin_account
- id / int
- user string
- password string
